
import React from "react";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./css/globals.css";
import { Flowbite, ThemeModeScript } from "flowbite-react";
import customTheme from "@/utils/theme/custom-theme";
import { CustomizerContextProvider } from "@/app/context/customizerContext";
import '../utils/i18n';
import SessionProviderComp from "./components/nextauth/SessionProvider";
import NextTopLoader from 'nextjs-toploader';
const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });
import { AuthProvider } from '../app/context/AuthContext'


export const metadata: Metadata = {
  title: "Modernize - Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode;
  session: any
}) {
  return (

    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <ThemeModeScript />
      </head>
      <body className={`${plus_jakarta_sans.className}`}>
        <NextTopLoader />
        <Flowbite theme={{ theme: customTheme }}>
          <SessionProviderComp session={session}>
            <AuthProvider>
              <CustomizerContextProvider>
                {children}
              </CustomizerContextProvider>
            </AuthProvider>
          </SessionProviderComp>
        </Flowbite>
      </body>
    </html >

  );
}



